name: Build Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Extract zip
        run: |
          unzip -o simple-bridging-26.1.2.zip

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.8'

      - name: Build project
        run: gradle build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mod-JAR
          path: "**/build/libs/*.jar"
